exporter_port: $EXPORTER_PORT|9090 # the port that exposes cost metrics
polling_interval_seconds: $POLLING_INTERVAL_SECONDS|28800 # by default it is 8 hours

group_by:
  enabled: true
  groups:
    - type: Dimension
      name: ServiceName
      label_name: ServiceName
    - type: Dimension
      name: ResourceGroupName
      label_name: ResourceGroupName
  merge_minor_cost:
    # if this is enabled, minor cost that is below the threshold will be merged into one group
    enabled: false
    threshold: 10
    tag_value: other

target_azure_account:
  # Mandatory parameters
  Subscription: <mysubscriptionid>
  # Optional parameters, they translate to metric label, more can be added if needed
  ProjectName: myproject
  EnvironmentName: dev
